[book]
authors = ["李敖", "wjm_tcy"]
language = "zh"
multilingual = false
src = "./"
title = "大李敖全集"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/whatot/leeao"
git-branch = "master"

[output.html.print]
# print超过github上限50MB，于是默认关闭
enable = false

[output.html.search]
# search超过github上限100MB，于是默认关闭
enable = false
